# Generated by Django 5.0 on 2026-06-02 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_position', models.PositiveSmallIntegerField(default=0)),
                ('tier', models.PositiveSmallIntegerField(default=1)),
                ('crowns_earned', models.PositiveSmallIntegerField(default=0)),
                ('last_week_was_loss', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('seed', 'Seed of Beginning'), ('flame', 'Flame of Focus'), ('garden', 'Garden of Growth'), ('gem', 'Gem of Balance'), ('crown', 'Crown of Consistency'), ('phoenix', 'Phoenix of Return')], max_length=16)),
                ('tier', models.PositiveSmallIntegerField(default=1)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['earned_at'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('label', models.CharField(max_length=120)),
                ('focus', models.CharField(blank=True, max_length=500)),
                ('prize', models.CharField(blank=True, max_length=500)),
                ('core_rate', models.PositiveSmallIntegerField(default=0)),
                ('side_rate', models.PositiveSmallIntegerField(default=0)),
                ('weekly_score', models.PositiveSmallIntegerField(default=0)),
                ('is_win', models.BooleanField(default=False)),
                ('flame_average', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('is_current', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('core', 'Core'), ('side', 'Side')], max_length=8)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('goal', models.CharField(blank=True, max_length=500)),
                ('why', models.CharField(blank=True, max_length=500)),
                ('est_time', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('tracker_filled', models.PositiveSmallIntegerField(default=0)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.week')),
            ],
            options={
                'ordering': ['kind', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ScanUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('review', 'Review'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('ocr_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='planner.week')),
            ],
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.JSONField(default=list)),
                ('week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection', to='planner.week')),
            ],
        ),
        migrations.CreateModel(
            name='FlameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('focus', 'Focus'), ('leverage', 'Leverage'), ('alignment', 'Alignment'), ('momentum', 'Momentum'), ('energy', 'Energy'), ('fulfillment', 'Fulfillment')], max_length=16)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flame_ratings', to='planner.week')),
            ],
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('user', 'start_date'), name='unique_user_week_start'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('week', 'kind', 'sort_order')},
        ),
        migrations.AlterUniqueTogether(
            name='flamerating',
            unique_together={('week', 'dimension')},
        ),
    ]
